Add noindex header to beta documentation

diff --git a/.cloudcannon/prebuild b/.cloudcannon/prebuild
--- a/.cloudcannon/prebuild
+++ b/.cloudcannon/prebuild
@@ -1,3 +1,12 @@
+if [ -z "${SAFE_TO_DEINDEX+set}" ]
+then
+    if grep -iq "X-Robots-Tag" routing.json
+    then
+        echo "Failing build as an X-Robots-Tag was found but our SAFE_TO_DEINDEX variable has not been set"
+        exit 1
+    fi
+fi
+
 ./.cloudcannon/generate-versions > _data/systemversions.json
 node ./.cloudcannon/tidy-versions.js
 node ./.cloudcannon/download-permissions.js
